services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/lab8
    depends_on:
      - mongo
    restart: on-failure

  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

volumes:
  mongo-data:
